import * as stylex from "@stylexjs/stylex";
import { landingTokens as t } from "@/styles/tokens.stylex";

const FONT_SANS = "var(--font-geist-sans), system-ui, sans-serif";

export const styles = stylex.create({
  page: {
    minHeight: "100svh",
    color: t.ink,
    backgroundImage: `radial-gradient(circle at 8% 5%, rgba(255, 238, 216, 0.82), transparent 26rem), radial-gradient(circle at 92% 72%, rgba(171, 164, 255, 0.22), transparent 30rem), linear-gradient(180deg, #fffefa 0%, ${t.paper} 58%, #fffaf0 100%)`,
    fontFamily: FONT_SANS,
    letterSpacing: 0,
  },

  // ---- Header ----
  header: {
    position: "sticky",
    top: 0,
    zIndex: 20,
    display: "grid",
    gridTemplateColumns: "1fr auto 1fr auto",
    alignItems: "center",
    gap: "2rem",
    width: "min(100%, 78rem)",
    minHeight: "5rem",
    margin: "0 auto",
    padding: "1rem clamp(1.25rem, 3vw, 2.5rem)",
    backgroundColor: "rgba(255, 253, 248, 0.82)",
    backdropFilter: "blur(18px)",
    "@media (max-width: 980px)": {
      gridTemplateColumns: "1fr auto auto",
    },
    "@media (max-width: 640px)": {
      minHeight: "4.5rem",
      gap: "0.8rem",
      paddingInline: "1rem",
    },
  },
  logo: {
    display: "inline-flex",
    alignItems: "center",
    minHeight: "2rem",
    fontSize: "clamp(1.35rem, 2.4vw, 1.85rem)",
    fontWeight: 850,
    lineHeight: 1,
    letterSpacing: "-0.03em",
    "@media (max-width: 640px)": {
      fontSize: "1.45rem",
    },
  },
  nav: {
    display: "flex",
    alignItems: "center",
    gap: "clamp(1.5rem, 4vw, 4rem)",
    color: "#11151f",
    fontSize: "0.96rem",
    fontWeight: 520,
    "@media (max-width: 980px)": {
      display: "none",
    },
  },
  navLink: {
    ":hover": {
      color: "#6f64e8",
    },
  },
  primaryLink: {
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    gap: "0.9rem",
    minHeight: "3.25rem",
    whiteSpace: "nowrap",
    fontSize: "0.95rem",
    fontWeight: 720,
    justifySelf: "end",
    minWidth: "12rem",
    padding: "0 1.65rem",
    color: "#fff",
    backgroundImage: "linear-gradient(180deg, #222631 0%, #11151d 100%)",
    border: "1px solid rgba(255, 255, 255, 0.16)",
    borderRadius: "999px",
    boxShadow: "0 1rem 2rem rgba(17, 21, 29, 0.16)",
    ":hover": {
      transform: "translateY(-1px)",
      boxShadow: "0 1.15rem 2.2rem rgba(17, 21, 29, 0.2)",
    },
  },
  headerPrimaryLinkHidden: {
    "@media (max-width: 640px)": {
      display: "none",
    },
  },
  heroActionPrimaryLink: {
    "@media (max-width: 640px)": {
      width: "100%",
    },
  },
  secondaryLink: {
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    gap: "0.9rem",
    minHeight: "3.25rem",
    whiteSpace: "nowrap",
    fontSize: "0.95rem",
    fontWeight: 720,
    minWidth: "9.5rem",
    color: "#1e2431",
    ":hover": {
      color: "#6f64e8",
    },
    "@media (max-width: 640px)": {
      width: "100%",
    },
  },
  menuButton: {
    display: "inline-grid",
    placeItems: "center",
    gap: "0.35rem",
    width: "2.75rem",
    height: "2.75rem",
    padding: "0.75rem",
    backgroundColor: "transparent",
    borderWidth: 0,
    borderStyle: "none",
    borderColor: "transparent",
  },
  menuButtonBar: {
    display: "block",
    width: "1.25rem",
    height: "0.1rem",
    backgroundColor: t.ink,
    borderRadius: "999px",
  },

  // ---- Hero ----
  hero: {
    position: "relative",
    display: "grid",
    gridTemplateColumns: "minmax(0, 0.9fr) minmax(32rem, 1.1fr)",
    gap: "clamp(2rem, 5vw, 5rem)",
    alignItems: "center",
    width: "min(100%, 78rem)",
    minHeight: "clamp(41rem, 78svh, 48rem)",
    margin: "0 auto",
    padding: "clamp(2rem, 5vw, 4.5rem) clamp(1.25rem, 3vw, 2.5rem) 3rem",
    "@media (max-width: 980px)": {
      gridTemplateColumns: "1fr",
      minHeight: "auto",
      paddingTop: "2.5rem",
    },
    "@media (max-width: 640px)": {
      paddingInline: "1rem",
    },
  },
  heroCopy: {
    display: "grid",
    gap: "2rem",
    alignContent: "center",
    maxWidth: "31rem",
    "@media (max-width: 980px)": {
      maxWidth: "42rem",
    },
  },
  heroTitle: {
    position: "relative",
    width: "fit-content",
    fontSize: "clamp(4.4rem, 8vw, 6.5rem)",
    fontWeight: 500,
    lineHeight: 0.98,
    letterSpacing: 0,
    whiteSpace: "nowrap",
    margin: 0,
    "@media (max-width: 640px)": {
      fontSize: "clamp(3.2rem, 17vw, 4.5rem)",
    },
  },
  inWordsImage: {
    width: "100%",
    height: "auto",
    margin: 0,
    objectFit: "contain",
    objectPosition: "center",
  },
  heroLead: {
    maxWidth: "27rem",
    margin: 0,
    fontSize: "clamp(1.25rem, 2vw, 1.55rem)",
    fontWeight: 720,
    lineHeight: 1.85,
    letterSpacing: "0.12em",
    "@media (max-width: 640px)": {
      fontSize: "1.08rem",
      letterSpacing: "0.06em",
    },
  },
  heroDescription: {
    maxWidth: "28rem",
    margin: 0,
    color: "#242936",
    fontSize: "1rem",
    fontWeight: 520,
    lineHeight: 2,
    letterSpacing: "0.05em",
  },
  heroActions: {
    display: "flex",
    flexWrap: "wrap",
    gap: "1.5rem",
    alignItems: "center",
    paddingTop: "0.8rem",
    "@media (max-width: 640px)": {
      alignItems: "stretch",
    },
  },
  heroVisual: {
    position: "relative",
    minHeight: "clamp(34rem, 56vw, 43rem)",
    "@media (max-width: 980px)": {
      minHeight: "35rem",
    },
    "@media (max-width: 640px)": {
      minHeight: "44rem",
    },
  },
  heroAura: {
    position: "absolute",
    zIndex: 0,
    objectFit: "cover",
    pointerEvents: "none",
    userSelect: "none",
    top: "-8.8rem",
    left: "-2.4rem",
    width: "min(53rem, 92%)",
    height: "auto",
    clipPath: "circle(26% at 50% 50%)",
    filter: "saturate(0.92) brightness(1.04)",
    "@media (max-width: 640px)": {
      top: "-0.4rem",
      left: "-31%",
      width: "44rem",
      maxWidth: "none",
    },
  },
  heroDots: {
    position: "absolute",
    zIndex: 0,
    objectFit: "cover",
    pointerEvents: "none",
    userSelect: "none",
    right: "2.6rem",
    bottom: "5.2rem",
    width: "6rem",
    height: "auto",
    objectPosition: "50% 50%",
    "@media (max-width: 640px)": {
      right: "0.4rem",
      bottom: "5.4rem",
      width: "7rem",
      height: "6rem",
    },
  },
  heroOval: {
    position: "absolute",
    zIndex: 0,
    objectFit: "cover",
    pointerEvents: "none",
    userSelect: "none",
    top: "29%",
    left: "5%",
    width: "min(13.5rem, 25%)",
    height: "auto",
    clipPath: "ellipse(22% 32% at 50% 50%)",
    opacity: 0.7,
    transform: "rotate(20deg)",
    "@media (max-width: 640px)": {
      top: "19rem",
      left: "-17%",
      width: "15rem",
    },
  },
  heroScribble: {
    position: "absolute",
    zIndex: 0,
    objectFit: "cover",
    pointerEvents: "none",
    userSelect: "none",
    top: "11.7rem",
    right: "0.4rem",
    width: "min(18rem, 33%)",
    height: "auto",
    objectPosition: "center",
    "@media (max-width: 640px)": {
      top: "10.8rem",
      right: "-0.9rem",
      width: "13rem",
    },
  },
  heroPost: {
    position: "absolute",
    zIndex: 2,
    display: "grid",
    gap: "1rem",
    width: "min(19rem, 42vw)",
    minHeight: "11rem",
    padding: "1.25rem",
    backgroundColor: "rgba(255, 253, 247, 0.88)",
    border: "1px solid rgba(255, 255, 255, 0.74)",
    borderRadius: "1.25rem",
    boxShadow: "0 1.8rem 4.5rem rgba(38, 34, 23, 0.14)",
    backdropFilter: "blur(24px)",
    "@media (max-width: 640px)": {
      width: "min(19rem, calc(100vw - 2rem))",
    },
  },
  heroPostText: {
    margin: 0,
    fontSize: "1.08rem",
    fontWeight: 720,
    lineHeight: 1.75,
    letterSpacing: "0.08em",
  },
  heroPostPrimary: {
    top: "5.5%",
    right: "15%",
    transform: "rotate(-2deg)",
    "@media (max-width: 640px)": {
      top: "1rem",
      right: 0,
    },
  },
  heroPostSecondary: {
    right: "6%",
    bottom: "28%",
    backgroundColor: "rgba(229, 225, 255, 0.9)",
    transform: "rotate(4deg)",
    "@media (max-width: 640px)": {
      top: "14rem",
      right: "0.2rem",
      bottom: "auto",
    },
  },
  heroPostTertiary: {
    bottom: "3%",
    left: "1%",
    transform: "rotate(0deg)",
    "@media (max-width: 640px)": {
      top: "27rem",
      bottom: "auto",
      left: 0,
    },
  },
  postMeta: {
    display: "grid",
    gridTemplateColumns: "auto 1fr auto",
    gap: "0.55rem",
    alignItems: "center",
    color: "#4b5362",
    fontSize: "0.78rem",
    fontWeight: 680,
  },
  postMetaTime: {
    color: "#9297a2",
    fontSize: "0.74rem",
    fontWeight: 520,
  },
  avatar: {
    display: "inline-grid",
    placeItems: "center",
    flex: "0 0 auto",
    width: "1.75rem",
    height: "1.75rem",
    color: "#fff",
    fontSize: "0.75rem",
    fontWeight: 780,
    backgroundImage: "linear-gradient(135deg, #1f2632, #8184ad)",
    borderRadius: "50%",
  },
  discoveryAvatar: {
    width: "1.45rem",
    height: "1.45rem",
    fontSize: "0.62rem",
  },
  musicPill: {
    display: "grid",
    gridTemplateColumns: "auto 1fr",
    gap: "0.72rem",
    alignItems: "center",
  },
  pillTitle: {
    display: "block",
    lineHeight: 1.35,
    fontSize: "0.78rem",
  },
  pillSubtitle: {
    display: "block",
    lineHeight: 1.35,
    color: "#5d6470",
    fontSize: "0.72rem",
  },
  trackArt: {
    position: "relative",
    overflow: "hidden",
    backgroundColor: "#e9e2d5",
    borderRadius: "0.45rem",
    width: "3rem",
    height: "3rem",
    "::after": {
      position: "absolute",
      inset: 0,
      content: '""',
      backgroundImage:
        "linear-gradient(rgba(255, 255, 255, 0.26), rgba(255, 255, 255, 0)), radial-gradient(circle at 70% 26%, rgba(255, 255, 255, 0.55), transparent 22%)",
    },
  },
  feedTrackArt: {
    width: "3.5rem",
    height: "3.5rem",
  },
  discoveryArt: {
    position: "relative",
    overflow: "hidden",
    backgroundColor: "#e9e2d5",
    borderRadius: "0.45rem",
    width: "100%",
    aspectRatio: "1",
    "::after": {
      position: "absolute",
      inset: 0,
      content: '""',
      backgroundImage:
        "linear-gradient(rgba(255, 255, 255, 0.26), rgba(255, 255, 255, 0)), radial-gradient(circle at 70% 26%, rgba(255, 255, 255, 0.55), transparent 22%)",
    },
    "@media (max-width: 640px)": {
      gridRow: "span 5",
    },
  },
  artCoast: {
    backgroundImage:
      "linear-gradient(180deg, rgba(187, 234, 240, 0.85) 0 45%, rgba(129, 197, 219, 0.88) 45% 60%, #86bad0 60% 100%), radial-gradient(circle at 72% 22%, rgba(255, 212, 157, 0.8), transparent 22%)",
  },
  artForest: {
    backgroundImage:
      "linear-gradient(145deg, rgba(45, 80, 62, 0.94), rgba(73, 126, 100, 0.86)), radial-gradient(circle at 52% 34%, rgba(229, 210, 133, 0.76), transparent 30%)",
  },
  artPastel: {
    backgroundImage:
      "radial-gradient(circle at 26% 28%, #c2b5ff 0 18%, transparent 19%), radial-gradient(circle at 70% 62%, #ffd3ac 0 20%, transparent 21%), linear-gradient(135deg, #f4a7c3, #9fceef)",
  },
  artDusk: {
    backgroundImage:
      "linear-gradient(180deg, #473d94 0%, #c24d87 46%, #1e354d 100%), radial-gradient(circle at 22% 24%, rgba(255, 203, 112, 0.9), transparent 22%)",
  },
  artGreen: {
    backgroundImage:
      "linear-gradient(140deg, #163a36, #659b76 54%, #d7c98b), radial-gradient(circle at 70% 24%, rgba(245, 232, 172, 0.78), transparent 20%)",
  },
  artWindow: {
    backgroundImage:
      "linear-gradient(105deg, #c49398 0 38%, #f4d4c5 38% 55%, #8a5d72 55% 100%), radial-gradient(circle at 38% 42%, rgba(255, 235, 212, 0.85), transparent 26%)",
  },
  artRoom: {
    backgroundImage:
      "linear-gradient(90deg, #d4d8d0 0 34%, #eff0e8 34% 60%, #a8b0a6 60% 100%), radial-gradient(circle at 30% 72%, rgba(255, 255, 255, 0.72), transparent 30%)",
  },
  heroNote: {
    position: "absolute",
    right: "2.5rem",
    bottom: "0.2rem",
    zIndex: 3,
    maxWidth: "14rem",
    margin: 0,
    fontSize: "1.08rem",
    fontWeight: 640,
    lineHeight: 1.75,
    letterSpacing: "0.16em",
    "::after": {
      display: "block",
      width: "7rem",
      height: "0.08rem",
      margin: "0.35rem 0 0 auto",
      content: '""',
      backgroundColor: "#1d2330",
      borderRadius: "999px",
      transform: "rotate(-5deg)",
    },
    "@media (max-width: 640px)": {
      right: "0.5rem",
      bottom: 0,
      maxWidth: "11rem",
      fontSize: "0.94rem",
    },
  },

  // ---- How it works ----
  howItWorks: {
    display: "grid",
    gridTemplateColumns: "minmax(18rem, 0.9fr) minmax(18rem, 0.7fr) minmax(9rem, 0.45fr)",
    gap: "clamp(2.5rem, 7vw, 6rem)",
    alignItems: "center",
    width: "100%",
    padding:
      "clamp(3rem, 6vw, 5rem) max(clamp(1.25rem, 6vw, 7rem), calc((100vw - 78rem) / 2 + 2.5rem))",
    borderTopWidth: "1px",
    borderTopStyle: "solid",
    borderTopColor: t.line,
    borderBottomWidth: "1px",
    borderBottomStyle: "solid",
    borderBottomColor: t.line,
    backgroundImage:
      "radial-gradient(circle at 86% 85%, rgba(186, 176, 255, 0.34), transparent 18rem), radial-gradient(circle at 76% 90%, rgba(244, 165, 183, 0.25), transparent 13rem)",
    "@media (max-width: 980px)": {
      gridTemplateColumns: "1fr",
    },
    "@media (max-width: 640px)": {
      paddingInline: "1rem",
    },
  },
  sectionCopy: {
    display: "grid",
    alignContent: "start",
    gap: "1.25rem",
  },
  kicker: {
    color: "#8177ec",
    fontSize: "0.84rem",
    fontWeight: 760,
    letterSpacing: "0.08em",
  },
  sectionTitle: {
    fontSize: "clamp(2rem, 4vw, 2.75rem)",
    fontWeight: 680,
    lineHeight: 1.35,
    letterSpacing: "0.04em",
  },
  steps: {
    display: "grid",
    gap: "1.5rem",
    marginTop: "0.4rem",
    listStyle: "none",
  },
  stepItem: {
    display: "grid",
    gridTemplateColumns: "3rem 1fr",
    gap: "1.1rem",
    alignItems: "start",
    "@media (max-width: 640px)": {
      gridTemplateColumns: "2.7rem 1fr",
    },
  },
  stepNumber: {
    display: "grid",
    placeItems: "center",
    width: "2.85rem",
    height: "2.85rem",
    fontWeight: 720,
    backgroundColor: t.violetSoft,
    borderRadius: "50%",
  },
  stepNumber2: {
    backgroundColor: "#ffe0a7",
  },
  stepNumber3: {
    backgroundColor: "#ffc0c4",
  },
  stepTitle: {
    marginBottom: "0.45rem",
    fontSize: "1.04rem",
    fontWeight: 780,
    letterSpacing: "0.04em",
  },
  stepText: {
    margin: 0,
    color: "#242936",
    fontSize: "0.94rem",
    fontWeight: 520,
    lineHeight: 1.95,
    letterSpacing: "0.03em",
  },

  // ---- Phone mock ----
  phoneMock: {
    position: "relative",
    display: "grid",
    gridTemplateRows: "auto 1fr auto",
    width: "min(100%, 22.5rem)",
    minHeight: "31rem",
    padding: "1.35rem 1.45rem 1rem",
    overflow: "hidden",
    backgroundColor: "rgba(255, 253, 247, 0.9)",
    borderWidth: "0.55rem",
    borderStyle: "solid",
    borderColor: "rgba(255, 255, 255, 0.72)",
    borderRadius: "2.5rem",
    boxShadow: "inset 0 0 0 1px rgba(23, 27, 38, 0.06), 0 1.6rem 4rem rgba(64, 42, 89, 0.14)",
    justifySelf: "center",
    "@media (max-width: 980px)": {
      width: "min(100%, 24rem)",
    },
    "@media (max-width: 640px)": {
      minHeight: "29rem",
      padding: "1.1rem 1rem 0.7rem",
      borderWidth: "0.42rem",
      borderRadius: "2rem",
    },
  },
  phoneTexture: {
    position: "absolute",
    inset: "-6rem auto auto -9rem",
    zIndex: 0,
    width: "34rem",
    height: "auto",
    opacity: 0.34,
    pointerEvents: "none",
    transform: "scale(1.2)",
  },
  phoneHeader: {
    position: "relative",
    zIndex: 1,
    display: "grid",
    gridTemplateColumns: "1fr 1fr auto",
    alignItems: "center",
    minHeight: "2.4rem",
    color: "#686e7a",
    fontSize: "0.92rem",
  },
  phoneHeaderActive: {
    position: "relative",
    color: t.ink,
    "::after": {
      position: "absolute",
      bottom: "-0.6rem",
      left: 0,
      width: "2.15rem",
      height: "0.12rem",
      content: '""',
      backgroundColor: t.ink,
      borderRadius: "999px",
    },
  },
  phoneFeed: {
    position: "relative",
    zIndex: 1,
    display: "grid",
    alignContent: "start",
    gap: "1.55rem",
    padding: "1.5rem 0",
  },
  feedPost: {
    display: "grid",
    gap: "0.85rem",
  },
  feedUser: {
    display: "flex",
    gap: "0.65rem",
    alignItems: "center",
  },
  feedUserName: {
    display: "block",
    lineHeight: 1.25,
    fontSize: "0.78rem",
  },
  feedUserTime: {
    display: "block",
    lineHeight: 1.25,
    color: "#878c96",
    fontSize: "0.72rem",
  },
  feedPostText: {
    margin: 0,
    paddingLeft: "2.4rem",
    fontSize: "0.98rem",
    fontWeight: 700,
    lineHeight: 1.7,
    letterSpacing: "0.04em",
    "@media (max-width: 640px)": {
      paddingLeft: 0,
    },
  },
  feedTrack: {
    position: "relative",
    zIndex: 1,
    display: "grid",
    gridTemplateColumns: "auto 1fr auto",
    gap: "0.72rem",
    alignItems: "center",
    marginLeft: "2.4rem",
    paddingTop: "0.55rem",
    paddingRight: "0.7rem",
    paddingBottom: "0.55rem",
    paddingLeft: "0.55rem",
    backgroundColor: "rgba(255, 255, 255, 0.72)",
    borderRadius: "0.45rem",
    boxShadow: "0 0.7rem 1.6rem rgba(23, 27, 38, 0.07)",
    "@media (max-width: 640px)": {
      marginLeft: 0,
      paddingLeft: 0,
    },
  },
  feedPlayButton: {
    display: "grid",
    placeItems: "center",
    width: "2rem",
    height: "2rem",
    color: "#1f2430",
    fontSize: "0.75rem",
    backgroundColor: "#fff",
    borderWidth: 0,
    borderStyle: "none",
    borderColor: "transparent",
    borderRadius: "50%",
    boxShadow: "0 0.45rem 1rem rgba(23, 27, 38, 0.1)",
  },
  phoneNav: {
    position: "relative",
    zIndex: 1,
    display: "grid",
    gridTemplateColumns: "repeat(5, 1fr)",
    alignItems: "center",
    minHeight: "3.4rem",
    color: "#11151f",
    fontSize: "1.35rem",
    textAlign: "center",
  },
  phoneNavAdd: {
    display: "grid",
    placeItems: "center",
    width: "2.7rem",
    height: "2.7rem",
    margin: "0 auto",
    color: "#fff",
    backgroundColor: "#151a24",
    borderRadius: "50%",
  },

  // ---- Side statement ----
  sideStatement: {
    position: "relative",
    maxWidth: "11rem",
    margin: 0,
    padding: "4.8rem 0",
    fontSize: "1.35rem",
    fontWeight: 560,
    lineHeight: 1.18,
    "::before": {
      position: "absolute",
      left: "0.2rem",
      top: 0,
      width: "0.5rem",
      height: "0.5rem",
      content: '""',
      backgroundColor: "#bec0c8",
      borderRadius: "50%",
    },
    "::after": {
      position: "absolute",
      left: "0.2rem",
      bottom: 0,
      width: "0.5rem",
      height: "0.5rem",
      content: '""',
      backgroundColor: "#bec0c8",
      borderRadius: "50%",
    },
    "@media (max-width: 980px)": {
      maxWidth: "22rem",
      padding: "0 0 0 3rem",
    },
  },

  // ---- Discovery ----
  discovery: {
    display: "grid",
    gridTemplateColumns: "minmax(15rem, 0.72fr) minmax(0, 1.9fr)",
    gap: "clamp(2rem, 4vw, 3.5rem)",
    alignItems: "start",
    width: "min(100%, 78rem)",
    margin: "0 auto",
    padding: "clamp(3rem, 6vw, 4.5rem) clamp(1.25rem, 3vw, 2.5rem)",
    "@media (max-width: 980px)": {
      gridTemplateColumns: "1fr",
    },
    "@media (max-width: 640px)": {
      paddingInline: "1rem",
    },
  },
  discoveryIntro: {
    display: "grid",
    alignContent: "start",
    gap: "1.25rem",
  },
  discoveryIntroText: {
    maxWidth: "19rem",
    margin: 0,
    color: "#2b303d",
    fontSize: "0.98rem",
    fontWeight: 520,
    lineHeight: 1.95,
  },
  discoveryLink: {
    display: "inline-flex",
    gap: "0.8rem",
    alignItems: "center",
    width: "fit-content",
    marginTop: "1rem",
    color: "#8177ec",
    fontSize: "0.9rem",
    fontWeight: 760,
    ":hover": {
      color: "#6f64e8",
    },
  },
  discoveryGrid: {
    display: "grid",
    gridTemplateColumns: "repeat(4, minmax(0, 1fr))",
    gap: "clamp(1rem, 2vw, 2rem)",
    "@media (max-width: 980px)": {
      gridTemplateColumns: "repeat(2, minmax(0, 1fr))",
    },
    "@media (max-width: 640px)": {
      gridTemplateColumns: "1fr",
    },
  },
  discoveryCard: {
    display: "grid",
    gap: "0.7rem",
    minWidth: 0,
    "@media (max-width: 640px)": {
      gridTemplateColumns: "7rem 1fr",
      columnGap: "1rem",
      alignItems: "start",
    },
  },
  discoveryCardTitle: {
    minHeight: "1.3rem",
    overflowWrap: "anywhere",
    fontSize: "0.92rem",
    fontWeight: 760,
    lineHeight: 1.45,
    margin: 0,
  },
  discoveryCardArtist: {
    margin: 0,
    color: "#4d5360",
    fontSize: "0.78rem",
    fontWeight: 560,
    lineHeight: 1.35,
  },
  discoveryMeta: {
    display: "grid",
    gridTemplateColumns: "auto 1fr auto auto",
    gap: "0.48rem",
    alignItems: "center",
    minHeight: "1.9rem",
    color: "#4f5663",
    fontSize: "0.75rem",
    fontWeight: 650,
  },
  heartIcon: {
    color: "#f08a9a",
  },
  discoveryCardQuote: {
    margin: 0,
    color: "#202633",
    fontSize: "0.92rem",
    fontWeight: 560,
    lineHeight: 1.75,
    letterSpacing: "0.04em",
  },

  // ---- Final CTA ----
  finalCta: {
    position: "relative",
    display: "grid",
    gridTemplateColumns: "minmax(0, 1fr) auto",
    gap: "2rem",
    alignItems: "center",
    minHeight: "15rem",
    padding: "3.5rem max(clamp(1.25rem, 6vw, 7rem), calc((100vw - 78rem) / 2 + 2.5rem))",
    overflow: "hidden",
    borderTopWidth: "1px",
    borderTopStyle: "solid",
    borderTopColor: t.line,
    "@media (max-width: 980px)": {
      gridTemplateColumns: "1fr",
      justifyItems: "start",
    },
    "@media (max-width: 640px)": {
      paddingInline: "1rem",
    },
  },
  ctaPurpleAura: {
    position: "absolute",
    pointerEvents: "none",
    userSelect: "none",
    bottom: "-10rem",
    left: "-4.5rem",
    width: "min(39rem, 66vw)",
    height: "auto",
    "@media (max-width: 640px)": {
      bottom: "-8.8rem",
      left: "-9rem",
      width: "28rem",
      maxWidth: "none",
    },
  },
  ctaPinkOrb: {
    position: "absolute",
    pointerEvents: "none",
    userSelect: "none",
    bottom: "2.7rem",
    left: "6.2rem",
    width: "min(7.5rem, 15vw)",
    height: "auto",
    clipPath: "circle(37% at 50% 50%)",
    "@media (max-width: 640px)": {
      bottom: "7.8rem",
      left: "4.1rem",
      width: "5.6rem",
    },
  },
  ctaGoldOrb: {
    position: "absolute",
    pointerEvents: "none",
    userSelect: "none",
    bottom: "-4.3rem",
    left: "10.2rem",
    width: "min(12rem, 22vw)",
    height: "auto",
    clipPath: "circle(29% at 50% 52%)",
    filter: "saturate(0.72) brightness(1.08) blur(0.4px)",
    "@media (max-width: 640px)": {
      bottom: "3.1rem",
      left: "8.4rem",
      width: "8.8rem",
    },
  },
  finalCtaText: {
    position: "relative",
    zIndex: 1,
    justifySelf: "center",
    maxWidth: "37rem",
    margin: 0,
    fontSize: "clamp(1.45rem, 3vw, 2rem)",
    fontWeight: 720,
    lineHeight: 1.8,
    letterSpacing: "0.08em",
    "@media (max-width: 980px)": {
      justifySelf: "start",
    },
  },
  finalCtaActions: {
    position: "relative",
    zIndex: 1,
    display: "grid",
    gap: "1rem",
    justifyItems: "center",
  },
  finalCtaSmall: {
    color: "#2b303d",
    fontSize: "0.82rem",
    fontWeight: 650,
    letterSpacing: "0.08em",
    "@media (max-width: 640px)": {
      textAlign: "center",
    },
  },

  // ---- Footer ----
  footer: {
    display: "grid",
    gridTemplateColumns: "auto 1fr auto",
    gap: "2rem",
    alignItems: "center",
    width: "min(100%, 78rem)",
    margin: "0 auto",
    padding: "2rem clamp(1.25rem, 3vw, 2.5rem)",
    "@media (max-width: 980px)": {
      gridTemplateColumns: "1fr",
    },
    "@media (max-width: 640px)": {
      paddingInline: "1rem",
    },
  },
  footerNav: {
    display: "flex",
    flexWrap: "wrap",
    gap: "clamp(1rem, 3vw, 2.5rem)",
    alignItems: "center",
    justifyContent: "center",
    color: "#596070",
    fontSize: "0.78rem",
    fontWeight: 560,
    "@media (max-width: 980px)": {
      justifyContent: "flex-start",
    },
  },
  footerLink: {
    ":hover": {
      color: "#6f64e8",
    },
  },
  socialLinks: {
    display: "flex",
    flexWrap: "wrap",
    gap: "clamp(1rem, 3vw, 2.5rem)",
    alignItems: "center",
    justifyContent: "flex-end",
    color: "#11151f",
    fontSize: "1.25rem",
    fontWeight: 720,
    "@media (max-width: 980px)": {
      justifyContent: "flex-start",
    },
  },
});
