import * as stylex from "@stylexjs/stylex";
import { formTokens as f, colorTokens as c } from "./tokens.stylex";

export const shared = stylex.create({
  centeredPage: {
    display: "grid",
    placeItems: "center",
    minHeight: "100dvh",
    padding: "2rem",
    backgroundColor: c.background,
    color: c.foreground,
  },
  card: {
    width: "100%",
    maxWidth: "32rem",
    padding: "2rem",
    borderWidth: "1px",
    borderStyle: "solid",
    borderColor: f.inputBorder,
    borderRadius: "0.75rem",
    backgroundColor: f.white,
  },
  accountCard: {
    maxWidth: "40rem",
    borderRadius: "1rem",
    display: "grid",
    gap: "1rem",
  },
  cardBgTinted: {
    backgroundColor: "#f6f7fb",
  },
  fieldGroup: {
    display: "grid",
    gap: "0.5rem",
  },
  input: {
    padding: "0.75rem",
    borderRadius: "0.5rem",
    borderWidth: "1px",
    borderStyle: "solid",
    borderColor: f.inputBorder,
  },
  errorText: {
    margin: 0,
    color: f.errorRed,
  },
  submitButton: {
    padding: "0.75rem 1rem",
    borderRadius: "0.5rem",
    borderWidth: 0,
    borderStyle: "none",
    borderColor: "transparent",
  },
  secondaryButton: {
    padding: "0.75rem 1rem",
    borderRadius: "0.5rem",
    borderWidth: "1px",
    borderStyle: "solid",
    borderColor: f.inputBorder,
    backgroundColor: f.white,
  },
  dangerButton: {
    padding: "0.75rem 1rem",
    borderRadius: "0.5rem",
    borderWidth: 0,
    borderStyle: "none",
    borderColor: "transparent",
    backgroundColor: f.errorRed,
    color: f.white,
  },
  formGrid: {
    display: "grid",
    gap: "1rem",
  },
  gap3: {
    display: "grid",
    gap: "0.75rem",
  },
  marginTop1: {
    marginTop: "1rem",
  },
  googleButton: {
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    gap: "0.5rem",
    padding: "0.75rem 1rem",
    borderRadius: "0.5rem",
    borderWidth: "1px",
    borderStyle: "solid",
    borderColor: f.inputBorder,
    backgroundColor: f.white,
    color: f.darkText,
    textDecoration: "none",
    fontSize: "1rem",
    cursor: "pointer",
    width: "100%",
    boxSizing: "border-box",
  },
  cardTitle: {
    marginTop: 0,
    marginBottom: "0.75rem",
  },
  cardLead: {
    marginTop: 0,
    marginBottom: "1rem",
    lineHeight: 1.5,
  },
  welcomeText: {
    margin: 0,
    lineHeight: 1.5,
  },
  usernameText: {
    margin: 0,
    lineHeight: 1.5,
  },
  errorPageBg: {
    backgroundColor: "#f7f7f3",
    color: "#171717",
  },
  errorSection: {
    display: "grid",
    gap: "1rem",
    width: "100%",
    maxWidth: "34rem",
  },
  errorLabel: {
    color: "#6b6b63",
    fontSize: "0.875rem",
    margin: 0,
  },
  errorHeading: {
    fontSize: "2rem",
    lineHeight: 1.15,
    margin: 0,
  },
  errorBody: {
    color: "#4b4b45",
    lineHeight: 1.6,
    margin: 0,
  },
  errorRetryButton: {
    justifySelf: "start",
    minHeight: "2.75rem",
    padding: "0 1rem",
    borderRadius: "0.5rem",
    borderWidth: "1px",
    borderStyle: "solid",
    borderColor: "#171717",
    background: "#171717",
    color: "#ffffff",
    font: "inherit",
    cursor: "pointer",
  },
});
